version: '3'
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    hostname: syncthing
    volumes:
      - ./data:/var/syncthing
  web:
    # image: php:8.0-apache
    build: .
    container_name: web
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    user: "1000:1000"
    volumes:
      - ./ssl:/etc/apache2/ssl
      - ./data/Sync:/var/www/html/file/
      - ./frontend:/var/www/html/
    depends_on:
      - syncthing
    command: bash -c "sleep 5 && apache2-foreground"